### ISSUE TITLE
Documentation Discussion

### ISSUE THREAD

**Issue by sarfarazit08** [sarfarazit08/github-project-playground#6]
Let's work on the documentation together @sarfarazit08 

- [x] #7
- [x] #8
- [x] #9
- [x] Decide if we want to go with more complex plateforms like Google Docs or Confluence for real-time updates and feedback.

**Comment by sarfarazit08** [comment]
Hi Team, I wonder what we should do for documentation on this project.
Any thoughts @officialmail00786 💡

**Comment by officialmail00786** [comment]
Hi @sarfarazit08, I suggest creating a comprehensive project documentation that includes clear objectives, scope, milestones, and technical details. We can use a collaborative platform like Google Docs or Confluence for real-time updates and feedback. Let's also establish a documentation review process to ensure accuracy and completeness. Open to your ideas! 💡

**Comment by sarfarazit08** [comment]
so what we need basically is :

- [ ] Create a 'docs' folder
- [ ] Create a new 'index.md' document
- [ ] Turn On GitHub Pages
- [ ] Decide if we want to go with more complex plateforms like Google Docs or Confluence for real-time updates and feedback.

**Comment by officialmail00786** [comment]
Let's work on the documentation together @sarfarazit08 


- [ ] Create a 'docs' folder
- [ ] Create a new 'index.md' document
- [ ] Turn On GitHub Pages
- [ ] Decide if we want to go with more complex plateforms like Google Docs or Confluence for real-time updates and feedback.
